version: '3.8'

services:
  workout-db:
    image: mysql:8.0
    container_name: fitengine-workout-db
    environment:
      MYSQL_ROOT_PASSWORD: ParolaNoua123!
      MYSQL_DATABASE: FitEngine_WorkoutDb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: