// <auto-generated />
using System;
using FitEngine.Workout.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitEngine.Workout.Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutDbContext))]
    partial class WorkoutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FitEngine.Workout.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasName("PK_Workouts");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitEngine.Workout.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("exerciseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("targetMuscleGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("workoutId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasName("PK_WorkoutExercises");

                    b.HasIndex("workoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("FitEngine.Workout.Domain.Entities.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("RIR")
                        .HasColumnType("int");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasName("PK_WorkoutSets");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("FitEngine.Workout.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("FitEngine.Workout.Domain.Entities.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("workoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitEngine.Workout.Domain.Entities.WorkoutSet", b =>
                {
                    b.HasOne("FitEngine.Workout.Domain.Entities.WorkoutExercise", null)
                        .WithMany("sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitEngine.Workout.Domain.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitEngine.Workout.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Navigation("sets");
                });
#pragma warning restore 612, 618
        }
    }
}
